spring:
  datasource:
    url: jdbc:mysql://112.74.179.254:3306/laidian?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: laidian_java
    password: D3jmV5u9Ccc6fRVz
    initialSize: 10
    maxIdle: 20
    minIdle: 5
    maxActive: 200
    maxWait: 10000

    removeAbandoned: true
    removeAbandonedTimeout: 180

    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000

    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password: jnns
    database: 0
    timeout: 30000
logging:
  level:
    com.springboot.cxy.redis: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/**/*.xml

