spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: root
    initialSize: 10
    maxIdle: 20
    minIdle: 5
    maxActive: 200
    maxWait: 10000

    removeAbandoned: true
    removeAbandonedTimeout: 180

    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000

    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password: jnns
    database: 0
    timeout: 30000
logging:
  level:
    com.springboot.cxy.redis: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/**/*.xml

coco:
  interceptor:
    auth: true
    ignore:
      auth-ignore:
        - /test/index
      log-ignore:
  swagger:
    name: wocalie
    apis: com.test.base.controller
    desc: sda
    version: 1.0.0
  format:
    response-data: true
    des3: 123456
