spring:
  datasource:
    url: jdbc:mysql://112.74.179.254:3306/weather?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: weather
    password: 3H1HdBqrjtZ1GLCg
    initialSize: 10
    maxIdle: 20
    minIdle: 5
    maxActive: 200
    maxWait: 10000

    removeAbandoned: true
    removeAbandonedTimeout: 180

    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000

    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    host: 112.74.179.254
    port: 6379
    password: e8cFnj3CoWZdUFyXg8Dkv9Vp66c=
    database: 0
    timeout: 30000
logging:
  level:
    com.springboot.cachedemo: debug

